config/routes.rb
Rails.application.routes.draw do
  resources :forum_threads do
    resources :forum_posts    
  end
  devise_for :users

  root 'forum_threads#index'

end

app/models/forum_post.rb
class ForumPost < ActiveRecord::Base
  belongs_to :user
  belongs_to :forum_thread
end

app/models/forum_thread.rb
class ForumThread < ActiveRecord::Base
  belongs_to :user
  has_many :forum_posts
  has_many :users, through: :forum_posts
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :recepient, class_name: "User"
  belongs_to :actor, class_name: "User"
  belongs_to :notifiable, polymorphic: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :forum_threads
  has_many :forum_posts
  has_many :notifications, foreign_key: :recepient_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/forum_posts_controller.rb
class ForumPostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_forum_thread

  def create
    @forum_post = @forum_thread.forum_posts.new(forum_post_params)
    @forum_post.user = current_user
    if @forum_post.save

      # Create the notifications
      (@forum_thread.users.uniq - [current_user]).each do |user|
        Notification.create(recipient: user, actor: current_user, action: "posted", notifiable: @forum_post)
      end

      redirect_to @forum_thread
    else
      render "forum_threads/show"
    end
  end

  private

    def set_forum_thread
      @forum_thread = ForumThread.find(params[:forum_thread_id])
    end

    def forum_post_params
      params.require(:forum_post).permit(:body)
    end
end

app/controllers/forum_threads_controller.rb
class ForumThreadsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_forum_thread, only: [:show, :edit, :update, :destroy]

  def index
    @forum_threads = ForumThread.all
  end

  def show
    @forum_post = ForumPost.new
  end

  def new
    @forum_thread = ForumThread.new
  end

  def create
    @forum_thread = current_user.forum_threads.new(forum_thread_params)
    if @forum_thread.save
      redirect_to @forum_thread
    else
      render action: :new
    end
  end

  def edit
  end

  def update
    if @forum_thread.update(forum_thread_params)
      redirect_to @forum_thread
    else
      render action: :edit
    end
  end

  def destroy
    @forum_thread.destroy
    redirect_to forum_threads_path
  end

  private

    def set_forum_thread
      @forum_thread = ForumThread.find(params[:id])
    end

    def forum_thread_params
      params.require(:forum_thread).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forum_posts_helper.rb
module ForumPostsHelper
end

app/helpers/forum_threads_helper.rb
module ForumThreadsHelper
end

app/views/forum_posts/_form.html.erb
<%= form_for [@forum_thread, @forum_post] do |f| %>


  <div class="form-group">
    <%= f.label :body %><br>
    <%= f.text_field :body, class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/forum_posts/edit.html.erb
<h1>Editing Forum Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @forum_post %> |
<%= link_to 'Back', forum_posts_path %>

app/views/forum_posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Forum Posts</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @forum_posts.each do |forum_post| %>
      <tr>
        <td><%= forum_post.body %></td>
        <td><%= link_to 'Show', forum_post %></td>
        <td><%= link_to 'Edit', edit_forum_post_path(forum_post) %></td>
        <td><%= link_to 'Destroy', forum_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Forum post', new_forum_post_path %>

app/views/forum_posts/new.html.erb
<h1>New Forum Post</h1>

<%= render 'form' %>

<%= link_to 'Back', forum_posts_path %>

app/views/forum_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @forum_post.body %>
</p>

<%= link_to 'Edit', edit_forum_post_path(@forum_post) %> |
<%= link_to 'Back', forum_posts_path %>

app/views/forum_threads/_form.html.erb
<%= form_for(@forum_thread) do |f| %>
  <% if @forum_thread.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@forum_thread.errors.count, "error") %> prohibited this forum_thread from being saved:</h2>

      <ul>
      <% @forum_thread.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="form-group">
    <%= f.submit %>
  </div>
<% end %>

app/views/forum_threads/edit.html.erb
<h1>Editing Forum Thread</h1>

<%= render 'form' %>

<%= link_to 'Show', @forum_thread %> |
<%= link_to 'Back', forum_threads_path %>

app/views/forum_threads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Forum Threads</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @forum_threads.each do |forum_thread| %>
      <tr>
        <td><%= forum_thread.title %></td>
        <td><%= link_to 'Show', forum_thread %></td>
        <td><%= link_to 'Edit', edit_forum_thread_path(forum_thread) %></td>
        <td><%= link_to 'Destroy', forum_thread, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Forum thread', new_forum_thread_path %>

app/views/forum_threads/new.html.erb
<h1>New Forum Thread</h1>

<%= render 'form' %>

<%= link_to 'Back', forum_threads_path %>

app/views/forum_threads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @forum_thread.title %>
</p>
<hr>
<% @forum_thread.forum_posts.includes(:user).each do |forum_post| %>
  <div>
    <p><%= forum_post.user.email %> posted:</p>
    <%= simple_format forum_post.body %>
  </div>

  <hr />


<% end %>

<%= render partial: "forum_posts/form" %>

<%= link_to 'Edit', edit_forum_thread_path(@forum_thread) %> |
<%= link_to 'Back', forum_threads_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Notify</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container">
      <nav class="navbar-brand"><%= link_to "N0TiFy", root_path %></nav>
      <% if user_signed_in? %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to current_user.email %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        </ul>
      <% else %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Sign up",  new_user_registration_path %></li>
          <li><%= link_to "Sign in",  new_user_session_path %></li>
        </ul>
      <% end %>
    </div>
  </nav>

<%= yield %>

</body>
</html>